// Book catalog — prices and categories assigned to each title
const books = [
  // === Ficção / Aventura ===
  {
    id: 1,
    title: "Ladrão de Raios",
    image: "Ladrao de Raios.jpeg",
    category: "Ficção / Aventura",
    price: 24.90,
    description: "Uma aventura épica misturando mitologia grega com o mundo moderno.",
    condition: "Usado - Bom estado",
  },
  {
    id: 2,
    title: "Enfrentando o Dragão",
    image: "Enfrentando o Dragao.jpeg",
    category: "Ficção / Aventura",
    price: 24.90,
    description: "Uma jornada heroica cheia de coragem e fantasia.",
    condition: "Usado - Bom estado",
  },
  {
    id: 3,
    title: "O Resgate do Paladino",
    image: "O resgate do paladino.jpeg",
    category: "Ficção / Aventura",
    price: 22.90,
    description: "Uma missão de resgate em um mundo de fantasia medieval.",
    condition: "Usado - Bom estado",
  },
  {
    id: 4,
    title: "Crônicas de Chordata",
    image: "Cronicas de Chordata.jpeg",
    category: "Ficção / Aventura",
    price: 24.90,
    description: "Aventuras fascinantes no universo de Chordata.",
    condition: "Usado - Bom estado",
  },
  {
    id: 5,
    title: "O Enigma dos Dados",
    image: "Enigma Dos Dados.jpeg",
    category: "Ficção / Aventura",
    price: 24.90,
    description: "Um mistério envolvente que desafia a mente.",
    condition: "Usado - Bom estado",
  },
  {
    id: 6,
    title: "Sozinhos - Caçadores",
    image: "Sozinhos - Cacadores.jpeg",
    category: "Ficção / Aventura",
    price: 23.90,
    description: "Dois caçadores solitários enfrentam desafios inesperados.",
    condition: "Usado - Bom estado",
  },

  // === Série TMJ ===
  {
    id: 7,
    title: "TMJ - A Brigada dos Ossos",
    image: "TMJ- A brigada dos Ossos.jpeg",
    category: "Série TMJ",
    price: 20.00,
    description: "Primeiro livro da emocionante série TMJ.",
    condition: "Usado - Bom estado",
  },
  {
    id: 8,
    title: "TMJ - A Brigada dos Ossos 2",
    image: "TMJ- A brigada dos Ossos 2.jpeg",
    category: "Série TMJ",
    price: 20.00,
    description: "Continuação das aventuras da Brigada dos Ossos.",
    condition: "Usado - Bom estado",
  },
  {
    id: 9,
    title: "TMJ - Eu Sou Você",
    image: "TMJ- Eu sou voce.jpeg",
    category: "Série TMJ",
    price: 20.00,
    description: "Uma história de identidade e descobertas surpreendentes.",
    condition: "Usado - Bom estado",
  },
  {
    id: 10,
    title: "TMJ - Jogos Mortíferos",
    image: "TMJ- Jogos Mortiferos.jpeg",
    category: "Série TMJ",
    price: 20.00,
    description: "Jogos perigosos onde nada é o que parece.",
    condition: "Usado - Bom estado",
  },
  {
    id: 11,
    title: "TMJ - Nosso Filhote",
    image: "TMJ- Nosso filhote.jpeg",
    category: "Série TMJ",
    price: 20.00,
    description: "Uma história emocionante sobre laços e lealdade.",
    condition: "Usado - Bom estado",
  },
  {
    id: 12,
    title: "TMJ - Caçadores de Android",
    image: "TMJ_ Cacadores de Android.jpeg",
    category: "Série TMJ",
    price: 20.00,
    description: "Ficção científica intensa no universo TMJ.",
    condition: "Usado - Bom estado",
  },

  // === Literatura / Clássicos ===
  {
    id: 13,
    title: "O Pequeno Príncipe",
    image: "O Pequeno Principe.jpeg",
    category: "Literatura / Clássicos",
    price: 23.90,
    description: "O clássico atemporal de Antoine de Saint-Exupéry.",
    condition: "Usado - Bom estado",
  },
  {
    id: 14,
    title: "Fernão Capelo Gaivota",
    image: "Fernão Capelo Gaivota.jpeg",
    category: "Literatura / Clássicos",
    price: 18.90,
    description: "A fábula inspiradora sobre liberdade e perfeição.",
    condition: "Usado - Bom estado",
  },
  {
    id: 15,
    title: "O Cão dos Baskervilles",
    image: "O cao dos Baskervilles.jpeg",
    category: "Literatura / Clássicos",
    price: 21.90,
    description: "O famoso caso de Sherlock Holmes com o misterioso cão.",
    condition: "Usado - Bom estado",
  },
  {
    id: 16,
    title: "Marília de Dirceu",
    image: "Marilia de disceu.jpeg",
    category: "Literatura / Clássicos",
    price: 17.90,
    description: "Obra poética clássica da literatura brasileira.",
    condition: "Usado - Bom estado",
  },
  {
    id: 17,
    title: "Venha Ver o Pôr do Sol",
    image: "Venha ver o por do Sol.jpeg",
    category: "Literatura / Clássicos",
    price: 16.90,
    description: "Contos marcantes de Lygia Fagundes Telles.",
    condition: "Usado - Bom estado",
  },

  // === Literatura Brasileira ===
  {
    id: 18,
    title: "Carta de Achamento do Brasil",
    image: "Carta de Achamento do Brasil.jpeg",
    category: "Literatura Brasileira",
    price: 15.90,
    description: "O documento histórico que narra a chegada dos portugueses ao Brasil.",
    condition: "Usado - Bom estado",
  },
  {
    id: 19,
    title: "Cordel - História de Jeriquaquara",
    image: "Cordel Historia de Jeriquaquara.jpeg",
    category: "Literatura Brasileira",
    price: 12.90,
    description: "Poesia de cordel contando a história de Jericoacoara.",
    condition: "Usado - Bom estado",
  },
  {
    id: 20,
    title: "Cordel - O Segredo do Seu Lunga",
    image: "Cordel O Segredo do seu Lunga.jpeg",
    category: "Literatura Brasileira",
    price: 12.90,
    description: "Cordel nordestino cheio de mistério e tradição.",
    condition: "Usado - Bom estado",
  },
  {
    id: 21,
    title: "Tributo à Sua Memória",
    image: "Tributo a sua memoria.jpeg",
    category: "Literatura Brasileira",
    price: 18.90,
    description: "Uma homenagem emocionante em forma literária.",
    condition: "Usado - Bom estado",
  },

  // === Juvenil / Infanto-Juvenil ===
  {
    id: 22,
    title: "Meu Nome é Pedro",
    image: "Meu Nome e Pedro.jpeg",
    category: "Juvenil",
    price: 16.90,
    description: "Uma história encantadora para jovens leitores.",
    condition: "Usado - Bom estado",
  },
  {
    id: 23,
    title: "Enquanto Estamos Crescendo",
    image: "Enquanto Estamos Crecendo.jpeg",
    category: "Juvenil",
    price: 18.90,
    description: "Reflexões sobre a juventude e o crescimento.",
    condition: "Usado - Bom estado",
  },
  {
    id: 24,
    title: "O Diário Perdido",
    image: "O Diario Perdido.jpeg",
    category: "Juvenil",
    price: 20.90,
    description: "Um diário cheio de segredos e aventuras juvenis.",
    condition: "Usado - Bom estado",
  },
  {
    id: 25,
    title: "O Espião",
    image: "O espiao.jpeg",
    category: "Juvenil",
    price: 19.90,
    description: "Missões secretas e ação para jovens leitores.",
    condition: "Usado - Bom estado",
  },
  {
    id: 26,
    title: "Pokémon Atividades",
    image: "Pokemos Atividades.jpeg",
    category: "Juvenil",
    price: 9.90,
    description: "Livro de atividades temático Pokémon.",
    condition: "Usado - Bom estado",
  },
  {
    id: 27,
    title: "Karts",
    image: "Karts.jpeg",
    category: "Juvenil",
    price: 10.90,
    description: "Aventuras emocionantes no mundo das corridas de kart.",
    condition: "Usado - Bom estado",
  },
  {
    id: 28,
    title: "Histórias Curtas",
    image: "Historias Curtas.jpeg",
    category: "Juvenil",
    price: 13.90,
    description: "Coletânea de histórias curtas para jovens.",
    condition: "Usado - Bom estado",
  },
  {
    id: 29,
    title: "Longe como meu Querer",
    image: "Longe como meu Querer.jpeg",
    category: "Juvenil",
    price: 17.90,
    description: "Uma história de saudade e esperança.",
    condition: "Usado - Bom estado",
  },
  {
    id: 30,
    title: "Shurastey",
    image: "Shurastey.jpeg",
    category: "Juvenil",
    price: 19.90,
    description: "Uma aventura inesquecível de amizade e descobertas.",
    condition: "Usado - Bom estado",
  },

  // === Autoajuda / Espiritualidade ===
  {
    id: 31,
    title: "O Poder do Agora",
    image: "o poder do agora.jpeg",
    category: "Autoajuda",
    price: 28.90,
    description: "O bestseller de Eckhart Tolle sobre presença e consciência.",
    condition: "Usado - Bom estado",
  },
  {
    id: 32,
    title: "Poesia que Transforma",
    image: "Poesia que Transforma.jpeg",
    category: "Autoajuda",
    price: 16.90,
    description: "Poemas que tocam a alma e transformam a visão de mundo.",
    condition: "Usado - Bom estado",
  },

  // === Referência / Educação ===
  {
    id: 33,
    title: "Atlas Geográfico",
    image: "Atlas Geografico.jpeg",
    category: "Referência / Educação",
    price: 19.90,
    description: "Atlas completo com mapas detalhados do mundo.",
    condition: "Usado - Bom estado",
  },
  {
    id: 34,
    title: "Enciclopédia Brasileira",
    image: "Enciclopedia Brasileira.jpeg",
    category: "Referência / Educação",
    price: 39.90,
    description: "Enciclopédia abrangente sobre o Brasil.",
    condition: "Usado - Bom estado",
  },
  {
    id: 35,
    title: "Sistema Solar",
    image: "Sistema Solar.jpeg",
    category: "Referência / Educação",
    price: 14.90,
    description: "Guia ilustrado sobre os planetas e o universo.",
    condition: "Usado - Bom estado",
  },
  {
    id: 36,
    title: "Dicionário Português",
    image: "Dicionario- Portugues.jpeg",
    category: "Referência / Educação",
    price: 24.90,
    description: "Dicionário completo da língua portuguesa.",
    condition: "Usado - Bom estado",
  },
  {
    id: 37,
    title: "Mini-Dicionário Inglês",
    image: "Mini-Dicionario Ingles.jpeg",
    category: "Referência / Educação",
    price: 14.90,
    description: "Dicionário compacto inglês-português.",
    condition: "Usado - Bom estado",
  },
  {
    id: 38,
    title: "Guia de Sobrevivência na Natureza",
    image: "Guia de Sobrevivência na Natureza.jpeg",
    category: "Referência / Educação",
    price: 26.90,
    description: "Técnicas essenciais de sobrevivência ao ar livre.",
    condition: "Usado - Bom estado",
  },

  // === Culinária ===
  {
    id: 39,
    title: "Livro de Receitas Ana Maria",
    image: "Livro de Receitas Ana Maria.jpeg",
    category: "Culinária",
    price: 19.90,
    description: "Deliciosas receitas da apresentadora Ana Maria Braga.",
    condition: "Usado - Bom estado",
  },
  {
    id: 40,
    title: "Livro de Receitas Bolos",
    image: "Livro de Receitas Bolos.jpeg",
    category: "Culinária",
    price: 19.90,
    description: "As melhores receitas de bolos caseiros.",
    condition: "Usado - Bom estado",
  },
  {
    id: 41,
    title: "Livro de Receitas Chocolate Garoto",
    image: "Livro de Receitas Chocolate Garoto.jpeg",
    category: "Culinária",
    price: 18.90,
    description: "Receitas deliciosas com chocolate Garoto.",
    condition: "Usado - Bom estado",
  },
  {
    id: 42,
    title: "Livro de Receitas Cozinha Internacional",
    image: "Livro de Receitas Cozinha Internacional.jpeg",
    category: "Culinária",
    price: 19.90,
    description: "Pratos de todo o mundo na sua cozinha.",
    condition: "Usado - Bom estado",
  },
  {
    id: 43,
    title: "Livro de Receitas Docinhos",
    image: "Livro de Receitas Docinhos.jpeg",
    category: "Culinária",
    price: 17.90,
    description: "Receitas de docinhos para festas e comemorações.",
    condition: "Usado - Bom estado",
  },
  {
    id: 44,
    title: "Livro de Receitas Mondial",
    image: "Livro de Receitas Mondial.jpeg",
    category: "Culinária",
    price: 16.90,
    description: "Receitas práticas para o dia a dia.",
    condition: "Usado - Bom estado",
  },
  {
    id: 45,
    title: "Livro de Receitas Musse e Pavê",
    image: "Livro de Receitas Musse e Pave.jpeg",
    category: "Culinária",
    price: 17.90,
    description: "Sobremesas cremosas e irresistíveis.",
    condition: "Usado - Bom estado",
  },
  {
    id: 46,
    title: "Livro de Receitas Ofélia",
    image: "Livro de Receitas Ofelia.jpeg",
    category: "Culinária",
    price: 19.90,
    description: "O clássico livro de receitas da Ofélia.",
    condition: "Usado - Bom estado",
  },
  {
    id: 47,
    title: "Livro de Receitas Pizza",
    image: "Livro de Receitas Pizza.jpeg",
    category: "Culinária",
    price: 18.90,
    description: "Todas as variações de pizza para fazer em casa.",
    condition: "Usado - Bom estado",
  },
  {
    id: 48,
    title: "Livro de Receitas Tortas Geladas",
    image: "Livro de Receitas Tortas Geladas.jpeg",
    category: "Culinária",
    price: 17.90,
    description: "Tortas geladas deliciosas para qualquer ocasião.",
    condition: "Usado - Bom estado",
  },
    {
    id: 49,
    title: "Harry Potter - Serie Completa",
    image: "Harry-Potter Serie Completa.jpeg",
    category: "Fantasia/Aventura",
    price: 229.90,
    description: "Aventuras mágicas no mundo dos bruxos.",
    condition: "Usado - Bom estado",
  },
];

module.exports = books;
